database:
  psql:
    type: psql
    host: localhost
    port: 5432
    user: gamino
    password: password
    name: postgres
    sslmode: disable
  redis:
    host: localhost
    port: 6379
server:
  port: 9000
