apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${SERVICE_NAME}
      labels:
        app.snappcloud.io/name: ${SERVICE_NAME}
        app: ${SERVICE_NAME}
    spec:
      replicas: 1
      selector:
        app: ${SERVICE_NAME}
        deploymentconfig: ${SERVICE_NAME}
      strategy:
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      triggers: []
      template:
        metadata:
          labels:
            app: ${SERVICE_NAME}
            deploymentconfig: ${SERVICE_NAME}
        spec:
          containers:
            - name: test
              image: "registry.apps.private.teh-1.snappcloud.io/mozart/${SERVICE_NAME}:${SERVICE_IMAGE_TAG}"
              imagePullPolicy: Always
              resources:
                limits:
                  memory: 256Mi
              envFrom:
                - configMapRef:
                    name: ${SERVICE_NAME}
              ports:
                - containerPort: 9000
                  protocol: TCP
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          terminationGracePeriodSeconds: 30

parameters:
  - name: SERVICE_NAME
    displayName: Service Name
    description: The name used when creating the required deployment config, build config, service etc.
      Must be unique in your project, and contain only lower-case letters and numbers.
    value: "test"
    required: true
