apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app.snappcloud.io/name: ${SERVICE_NAME}
        app: ${SERVICE_NAME}
      name: ${SERVICE_NAME}
    spec:
      port:
        targetPort: ${SERVICE_NAME}-tcp
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Allow
      to:
        kind: Service
        name: ${SERVICE_NAME}

parameters:
  - name: SERVICE_NAME
    displayName: Service name
    required: true
    value: "test"
  - name: CREATED_BY
    displayName: Service name
    required: true
    value: "mozart"
  - name: SERVICE_NAMESPACE
    displayName: Application Unique ID
    required: true
    value: "mozart"
